#ifndef _HEADER_H_
#define _HEADER_H_


#define LOGIN_FREE 1		// REPONSE POSITIVE A LA REQUETE "REQ_VERIFY_LOGIN = $LOGIN"
#define LOGIN_BUSY 0		// REPONSE NEGATIVE A LA REQUETE "REQ_VERIFY_LOGIN = $LOGIN"





#endif